"""empty message

Revision ID: 0de8b8047a62
Revises: 58c5d6a302d9
Create Date: 2021-05-21 11:44:42.985066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de8b8047a62'
down_revision = '58c5d6a302d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_books',
    sa.Column('id_class_books', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_class_books')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_books')
    # ### end Alembic commands ###
