"""empty message

Revision ID: 58c5d6a302d9
Revises: 
Create Date: 2021-05-21 09:31:27.737555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c5d6a302d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id_author', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_table('book_authors',
    sa.Column('id_book_authors', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_book_authors')
    )
    op.create_table('books',
    sa.Column('id_book', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=True),
    sa.Column('id_subject', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_book')
    )
    op.create_table('classes',
    sa.Column('id_class', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('letter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_class')
    )
    op.create_table('subjects',
    sa.Column('id_subject', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_subject')
    )
    op.create_table('user_books',
    sa.Column('id_user_book', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_user_book')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id_class', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_books')
    op.drop_table('subjects')
    op.drop_table('classes')
    op.drop_table('books')
    op.drop_table('book_authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
