"""empty message

Revision ID: de5e01308bea
Revises: 93cbd1ae1cee
Create Date: 2021-05-21 17:26:22.583819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5e01308bea'
down_revision = '93cbd1ae1cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('num_class', sa.Integer(), nullable=True))
    op.drop_column('books', 'id_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id_class', sa.INTEGER(), nullable=True))
    op.drop_column('books', 'num_class')
    # ### end Alembic commands ###
